""":mod:`lsf_ibutils.ibsub.output` -- Command and script output formatting
"""
# This function has an interesting history of being undocumented, deprecated,
# etc. However, it seems to be portable across Python 2 and 3. See here:
# <http://docs.python.org/2/library/pipes.html#pipes.quote>
from pipes import quote


SYNTAXES = [
    'bash',
    'zsh',
    'tcsh',
    'ksh',
    'python',
]
"""Supported shell output syntaxes."""


def build_command(flags, command):
    """Build a bsub command string from a list of flags.

    :param flags: a list of flags
    :type flags: :class:`list` of :class:`tuple`
    :param command: command to run
    :type command: :class:`str`
    :return: the command string
    :rtype: :class:`str`
    """
    quoted_args = ['bsub']
    for flag_tuple in flags:
        for flag in flag_tuple:
            quoted_args.append(quote(flag))
    quoted_args.append(quote(command))
    return ' '.join(quoted_args)


class BuildScript(object):
    def __init__(self, today_datetime):
        self._today_datetime = today_datetime

    def __call__(self, flags, command, syntax):
        """Build a script string from a list of flags and given syntax.

        :param flags: a list of flags
        :type flags: :class:`list` of :class:`tuple`
        :param syntax: shell syntax to use
        :type syntax: :class:`str`, one of :data:`SHELLS`
        :param command: command to run
        :type command: :class:`str`
        :return: the script as a string
        :rtype: class:`str`
        """
        if syntax not in SYNTAXES:
            raise ValueError(
                'invalid shell syntax {0}, valid syntaxes are {1}'.format(
                    repr(syntax),
                    ', '.join([repr(s) for s in SYNTAXES])))
        formatted_time = self._today_datetime.strftime('%Y-%m-%d %H:%M:%S')
        lines = [
            '#!/usr/bin/env {0}'.format(syntax),
            '#',
            '# LSF batch script',
            '# Generated by ibsub on {0}'.format(formatted_time),
            '#'
        ]
        for flag_tuple in flags:
            lines.append('#BSUB {0}'.format(
                ' '.join([quote(flag) for flag in flag_tuple])))
        lines.append('')
        lines.append(quote(command))
        return '\n'.join(lines) + '\n'
